.global UROM_moveDP0
.equiv UROM_moveDP0, 0x8013
.global UROM_moveDP0inc
.equiv UROM_moveDP0inc, 0x8015
.global UROM_moveDP0dec
.equiv UROM_moveDP0dec, 0x8017
.global UROM_moveDP1
.equiv UROM_moveDP1, 0x8019
.global UROM_moveDP1inc
.equiv UROM_moveDP1inc, 0x801b
.global UROM_moveDP1dec
.equiv UROM_moveDP1dec, 0x801d
.global UROM_moveFP
.equiv UROM_moveFP, 0x801f
.global UROM_moveFPinc
.equiv UROM_moveFPinc, 0x8021
.global UROM_moveFPdec
.equiv UROM_moveFPdec, 0x8023
.global UROM_copyBuffer
.equiv UROM_copyBuffer, 0x8025
.global UROM_stopMode
.equiv UROM_stopMode, 0x8027
.global UROM_flashEraseAll
.equiv UROM_flashEraseAll, 0x802b
.global UROM_flashWrite
.equiv UROM_flashWrite, 0x802f
.global UROM_flashErasePage
.equiv UROM_flashErasePage, 0x8031
